#include "DisparityGame/GameProductionCatalog.h"

namespace DisparityGame
{
const std::array<ProductionFollowupPoint, V25ProductionPointCount>& GetV25ProductionPoints()
{
    static const std::array<ProductionFollowupPoint, V25ProductionPointCount> points = { {
        { "v25_point_01_editor_prefs_viewport_hud", "Editor", "Persist viewport HUD row visibility" },
        { "v25_point_02_editor_prefs_transform_precision", "Editor", "Persist transform precision settings" },
        { "v25_point_03_editor_prefs_command_filter", "Editor", "Persist command history filters" },
        { "v25_point_04_editor_prefs_dock_layout", "Editor", "Track dock layout preference readiness" },
        { "v25_point_05_editor_prefs_user_path", "Editor", "Track user preference storage path" },
        { "v25_point_06_viewport_toolbar_camera_mode", "Viewport", "Expose camera mode toolbar state" },
        { "v25_point_07_viewport_toolbar_render_debug", "Viewport", "Expose render debug toolbar state" },
        { "v25_point_08_viewport_toolbar_capture_state", "Viewport", "Expose capture toolbar state" },
        { "v25_point_09_viewport_toolbar_object_id_overlay", "Viewport", "Expose object-ID overlay toolbar state" },
        { "v25_point_10_viewport_toolbar_depth_overlay", "Viewport", "Expose depth overlay toolbar state" },
        { "v25_point_11_gizmo_depth_aware_hover", "Gizmo", "Track depth-aware gizmo hover readiness" },
        { "v25_point_12_gizmo_constraint_preview", "Gizmo", "Track gizmo constraint preview readiness" },
        { "v25_point_13_gizmo_numeric_entry", "Gizmo", "Track numeric transform entry readiness" },
        { "v25_point_14_gizmo_pivot_orientation_editing", "Gizmo", "Track pivot and orientation editing readiness" },
        { "v25_point_15_gizmo_handle_metadata", "Gizmo", "Track richer gizmo object-ID metadata" },
        { "v25_point_16_asset_gpu_mesh_upload", "Assets", "Validate cooked GPU mesh upload readiness" },
        { "v25_point_17_asset_texture_slot_binding", "Assets", "Validate material texture slot binding readiness" },
        { "v25_point_18_asset_animation_resources", "Assets", "Validate animation resource promotion readiness" },
        { "v25_point_19_asset_dependency_preview", "Assets", "Validate dependency invalidation preview readiness" },
        { "v25_point_20_asset_reload_rollback", "Assets", "Validate reload-safe rollback readiness" },
        { "v25_point_21_render_explicit_barriers", "Rendering", "Validate explicit render barrier diagnostics" },
        { "v25_point_22_render_alias_lifetime_validation", "Rendering", "Validate alias lifetime diagnostics" },
        { "v25_point_23_render_gpu_culling_plan", "Rendering", "Track GPU culling plan readiness" },
        { "v25_point_24_render_forward_plus_plan", "Rendering", "Track Forward+ light binning readiness" },
        { "v25_point_25_render_cascaded_shadow_plan", "Rendering", "Track cascaded shadow map readiness" },
        { "v25_point_26_capture_tiled_offscreen_plan", "Capture", "Validate tiled offscreen capture readiness" },
        { "v25_point_27_capture_resolve_filter_catalog", "Capture", "Validate capture resolve filter catalog readiness" },
        { "v25_point_28_capture_exr_output_plan", "Capture", "Track EXR output plan readiness" },
        { "v25_point_29_capture_async_compression_plan", "Capture", "Track async capture compression readiness" },
        { "v25_point_30_vfx_debug_visualizers", "VFX", "Validate VFX debug visualizer readiness" },
        { "v25_point_31_sequencer_curve_editor_plan", "Sequencer", "Track curve editor readiness" },
        { "v25_point_32_sequencer_clip_blending_plan", "Sequencer", "Track clip blending readiness" },
        { "v25_point_33_sequencer_bookmark_tracks", "Sequencer", "Validate bookmark track readiness" },
        { "v25_point_34_audio_streamed_music_plan", "Audio", "Track streamed music backend readiness" },
        { "v25_point_35_audio_content_pulse_plan", "Audio", "Validate content-driven pulse readiness" },
        { "v25_point_36_prod_golden_profile_expansion", "Production", "Validate golden profile expansion path" },
        { "v25_point_37_prod_schema_versioning", "Production", "Validate versioned runtime schema readiness" },
        { "v25_point_38_prod_interactive_ci_gate", "Production", "Validate interactive CI gate readiness" },
        { "v25_point_39_prod_installer_artifact", "Production", "Validate installer artifact readiness" },
        { "v25_point_40_prod_obs_websocket_automation", "Production", "Validate OBS automation readiness" }
    } };
    return points;
}

const std::array<ProductionFollowupPoint, V28DiversifiedPointCount>& GetV28DiversifiedPoints()
{
    static const std::array<ProductionFollowupPoint, V28DiversifiedPointCount> points = { {
        { "v28_point_01_editor_profile_import_export", "Editor", "Profile import/export path" },
        { "v28_point_02_editor_profile_diff", "Editor", "Profile diff summary" },
        { "v28_point_03_editor_dock_layout", "Editor", "Dock-layout persistence readiness" },
        { "v28_point_04_editor_workspace_presets", "Editor", "Workspace preset switching" },
        { "v28_point_05_editor_capture_progress", "Editor", "Viewport capture progress state" },
        { "v28_point_06_editor_command_macro_review", "Editor", "Reviewable command macro surface" },
        { "v28_point_07_asset_gpu_package_upload", "Assets", "Optimized GPU package promotion" },
        { "v28_point_08_asset_texture_bindings", "Assets", "Material texture binding readiness" },
        { "v28_point_09_asset_animation_clips", "Assets", "Animation clip resource readiness" },
        { "v28_point_10_asset_live_invalidation", "Assets", "Live dependency invalidation tickets" },
        { "v28_point_11_asset_reload_rollback_journal", "Assets", "Reload rollback journal" },
        { "v28_point_12_asset_streaming_priorities", "Assets", "Streaming priority queues" },
        { "v28_point_13_render_explicit_bind_barriers", "Rendering", "Explicit DX11 bind/unbind barrier diagnostics" },
        { "v28_point_14_render_alias_lifetime_validation", "Rendering", "Alias lifetime validation" },
        { "v28_point_15_render_gpu_culling_buckets", "Rendering", "GPU culling bucket readiness" },
        { "v28_point_16_render_forward_plus_bins", "Rendering", "Forward+ light bin readiness" },
        { "v28_point_17_render_csm_cascades", "Rendering", "Cascaded shadow cascade readiness" },
        { "v28_point_18_render_motion_vectors_taa", "Rendering", "Motion-vector and TAA resolve readiness" },
        { "v28_point_19_runtime_streaming_requests", "Runtime", "Asset streaming request surface" },
        { "v28_point_20_runtime_cancellation_tokens", "Runtime", "Async cancellation tokens" },
        { "v28_point_21_runtime_file_watchers", "Runtime", "File watcher readiness" },
        { "v28_point_22_runtime_script_reload_boundary", "Runtime", "Script reload boundary" },
        { "v28_point_23_runtime_script_state_slots", "Runtime", "Script state preservation slots" },
        { "v28_point_24_runtime_sequencer_preview", "Runtime", "Sequencer clip blending and keyboard preview" },
        { "v28_point_25_audio_xaudio2_mixer_targets", "Audio", "XAudio2 mixer voice targets" },
        { "v28_point_26_audio_streamed_music_asset", "Audio", "Streamed music asset surface" },
        { "v28_point_27_audio_spatial_components", "Audio", "Spatial emitter components" },
        { "v28_point_28_audio_attenuation_assets", "Audio", "Attenuation curve assets" },
        { "v28_point_29_audio_calibrated_meters", "Audio", "Calibrated production meters" },
        { "v28_point_30_audio_content_amplitude_pulses", "Audio", "Content-driven amplitude pulses" },
        { "v28_point_31_prod_per_gpu_goldens", "Production", "Per-GPU golden profiles" },
        { "v28_point_32_prod_baseline_diff_package", "Production", "Baseline diff package output" },
        { "v28_point_33_prod_schema_compatibility", "Production", "Schema compatibility surface" },
        { "v28_point_34_prod_interactive_runner", "Production", "Interactive runner plan" },
        { "v28_point_35_prod_signed_installer", "Production", "Signed installer artifact readiness" },
        { "v28_point_36_prod_obs_websocket_commands", "Production", "OBS WebSocket command automation" }
    } };
    return points;
}

const std::array<ProductionFollowupPoint, V29PublicDemoPointCount>& GetV29PublicDemoPoints()
{
    static const std::array<ProductionFollowupPoint, V29PublicDemoPointCount> points = { {
        { "v29_point_01_playable_objective_loop", "Gameplay", "Playable rift-stabilization objective loop" },
        { "v29_point_02_collectible_shards", "Gameplay", "Collectible echo shards around the arena" },
        { "v29_point_03_extraction_gate", "Gameplay", "Completion gate opens after shard collection" },
        { "v29_point_04_reset_hotkey", "Gameplay", "F10 public-demo reset path" },
        { "v29_point_05_sprint_energy", "Gameplay", "Shift sprint with visible focus energy" },
        { "v29_point_06_arena_bounds", "Gameplay", "Soft bounds keep the player in the demo space" },
        { "v29_point_07_shard_beacons", "Visuals", "Tall shard beacons for public readability" },
        { "v29_point_08_extraction_rings", "Visuals", "Charged extraction rings around the rift" },
        { "v29_point_09_sentinel_orbits", "Visuals", "Orbiting sentinel hazards create motion" },
        { "v29_point_10_player_trail", "Visuals", "Short player trail pips sell movement" },
        { "v29_point_11_reactive_rift_charge", "Visuals", "Rift intensity responds to collected shards" },
        { "v29_point_12_directional_hint_beam", "Visuals", "Objective hint beam points to the next shard" },
        { "v29_point_13_public_hud", "HUD", "Public demo HUD renders outside editor panels" },
        { "v29_point_14_progress_bars", "HUD", "Stability and focus bars are visible" },
        { "v29_point_15_objective_text", "HUD", "Objective text changes with demo state" },
        { "v29_point_16_timer_display", "HUD", "Run timer supports public attempts" },
        { "v29_point_17_status_feedback", "HUD", "Pickup/completion status feedback" },
        { "v29_point_18_controls_hint", "HUD", "Minimal controls hint for recording sessions" },
        { "v29_point_19_pickup_audio", "Audio", "Spatial pickup cue on shard collection" },
        { "v29_point_20_completion_audio", "Audio", "Completion cue when extraction succeeds" },
        { "v29_point_21_non_spam_audio", "Audio", "Cues fire only on state changes" },
        { "v29_point_22_audio_pulse_link", "Audio", "Demo charge contributes to rift beat response" },
        { "v29_point_23_showcase_framing", "Capture", "Showcase camera frames the playable objective field" },
        { "v29_point_24_trailer_readability", "Capture", "Trailer mode sees the charged rift objective" },
        { "v29_point_25_photo_ready_state", "Capture", "High-res capture includes demo indicators" },
        { "v29_point_26_runtime_metrics", "Verification", "Runtime report emits public-demo counters" },
        { "v29_point_27_baseline_gates", "Verification", "Baselines require public-demo coverage" },
        { "v29_point_28_schema_coverage", "Verification", "Runtime schema includes v29 metrics" },
        { "v29_point_29_manifest_review", "Verification", "Followup manifest review covers v29 points" },
        { "v29_point_30_release_docs", "Production", "Docs describe the playable public demo" }
    } };
    return points;
}

const std::array<ProductionFollowupPoint, V30VerticalSlicePointCount>& GetV30VerticalSlicePoints()
{
    static const std::array<ProductionFollowupPoint, V30VerticalSlicePointCount> points = { {
        { "v30_point_01_chained_objectives", "Gameplay", "Shard collection chains into phase-anchor alignment" },
        { "v30_point_02_phase_anchor_puzzle", "Gameplay", "Three phase anchors gate extraction" },
        { "v30_point_03_checkpoint_state", "Gameplay", "Public demo records checkpoint state" },
        { "v30_point_04_retry_failure", "Gameplay", "Stability failure retries from checkpoint" },
        { "v30_point_05_objective_distance", "Gameplay", "Next objective distance is tracked" },
        { "v30_point_06_stage_state_machine", "Gameplay", "Explicit public-demo stage machine" },
        { "v30_point_07_gamepad_surface", "Gameplay", "Gamepad-ready input surface is exposed" },
        { "v30_point_08_completion_gate_polish", "Gameplay", "Extraction requires anchors and completion polish" },
        { "v30_point_09_anchor_glyphs", "Visuals", "Phase anchors draw readable glyph rings" },
        { "v30_point_10_phase_bridges", "Visuals", "Activated anchors draw bridge beams to the rift" },
        { "v30_point_11_checkpoint_marker", "Visuals", "Checkpoint marker is visible in the arena" },
        { "v30_point_12_retry_warning_feedback", "Visuals", "Low-stability warning feedback is visible" },
        { "v30_point_13_route_beam_upgrade", "Visuals", "Objective beam follows shards, anchors, and extraction" },
        { "v30_point_14_public_hud_stage", "HUD", "HUD shows stage, anchors, checkpoint, and retries" },
        { "v30_point_15_demo_director_panel", "Editor", "Editor exposes a public Demo Director panel" },
        { "v30_point_16_director_reset_controls", "Editor", "Director can reset and checkpoint the vertical slice" },
        { "v30_point_17_event_telemetry", "Editor", "Recent public-demo events are inspectable" },
        { "v30_point_18_stage_readout", "Editor", "Current stage and objective telemetry are inspectable" },
        { "v30_point_19_readiness_table", "Editor", "Profiler exposes v30 readiness points" },
        { "v30_point_20_command_history_labels", "Editor", "Demo director actions enter command history" },
        { "v30_point_21_event_queue", "Backend", "Small event queue records gameplay state changes" },
        { "v30_point_22_checkpoint_snapshot", "Backend", "Checkpoint snapshots preserve stage progress" },
        { "v30_point_23_retry_telemetry", "Backend", "Retry counters are reported deterministically" },
        { "v30_point_24_route_telemetry", "Backend", "Objective-route telemetry is emitted" },
        { "v30_point_25_deterministic_validation", "Backend", "Runtime verifier completes the whole vertical slice" },
        { "v30_point_26_backend_schema", "Backend", "Runtime schema includes v30 vertical-slice metrics" },
        { "v30_point_27_vfx_charge_link", "Rendering", "Rift VFX intensity responds to anchor progress" },
        { "v30_point_28_beacon_draw_counters", "Rendering", "Anchor and checkpoint visuals contribute draw coverage" },
        { "v30_point_29_capture_readiness", "Capture", "Trailer/photo capture sees the new objective state" },
        { "v30_point_30_perf_history", "Production", "Performance history records v30 counters" },
        { "v30_point_31_manifest_review", "Verification", "v30 followup manifest is reviewed" },
        { "v30_point_32_baseline_gates", "Verification", "Baselines require v30 objective coverage" },
        { "v30_point_33_runtime_script_gate", "Verification", "Runtime wrapper asserts v30 report metrics" },
        { "v30_point_34_release_readiness", "Production", "Release readiness includes the v30 manifest" },
        { "v30_point_35_docs_updated", "Production", "Docs describe the v30 playable slice" },
        { "v30_point_36_roadmap_refresh", "Production", "Roadmap and agent context list next followups" }
    } };
    return points;
}

const std::array<ProductionFollowupPoint, V31DiversifiedPointCount>& GetV31DiversifiedPoints()
{
    static const std::array<ProductionFollowupPoint, V31DiversifiedPointCount> points = { {
        { "v31_point_01_editor_command_palette", "Editor", "Command palette/search surface is represented in editor telemetry" },
        { "v31_point_02_editor_viewport_bookmarks", "Editor", "Viewport bookmarks are available for show-off camera hops" },
        { "v31_point_03_editor_gizmo_constraint_preview", "Editor", "Gizmo constraint previews are exposed for precision edits" },
        { "v31_point_04_editor_macro_export", "Editor", "Command macro export review is tracked" },
        { "v31_point_05_editor_demo_bookmarks", "Editor", "Demo Director exposes vertical-slice bookmark telemetry" },
        { "v31_point_06_asset_gpu_upload_manifest", "AssetPipeline", "Optimized package upload manifest is represented" },
        { "v31_point_07_asset_material_bindings", "AssetPipeline", "Texture binding diagnostics cover material slots" },
        { "v31_point_08_asset_skeleton_retarget", "AssetPipeline", "Skeleton/retarget readiness is surfaced" },
        { "v31_point_09_asset_dependency_replay", "AssetPipeline", "Dependency invalidation replay queue is tracked" },
        { "v31_point_10_asset_stream_budget", "AssetPipeline", "Streaming priority budgets are tracked" },
        { "v31_point_11_render_bind_unbind_audit", "Rendering", "Render graph bind/unbind barrier audit is represented" },
        { "v31_point_12_render_alias_slot_audit", "Rendering", "Alias lifetime slots are audited" },
        { "v31_point_13_render_cluster_bins", "Rendering", "Clustered/Forward+ light-bin preview is tracked" },
        { "v31_point_14_render_csm_stability", "Rendering", "Cascaded shadow stabilization preview is tracked" },
        { "v31_point_15_render_vfx_debug", "Rendering", "VFX debug visualizer readiness is represented" },
        { "v31_point_16_runtime_resonance_gates", "Runtime", "Playable resonance gates extend the public demo" },
        { "v31_point_17_runtime_collision_volumes", "Runtime", "Collision/traversal volume checks are reported" },
        { "v31_point_18_runtime_controller_surface", "Runtime", "Controller/gamepad surface remains exposed" },
        { "v31_point_19_runtime_failure_screen", "Runtime", "Failure/retry screen telemetry is tracked" },
        { "v31_point_20_runtime_event_routing", "Runtime", "Gameplay event routing counters are reported" },
        { "v31_point_21_audio_footstep_cadence", "Audio", "Footstep cadence events are produced" },
        { "v31_point_22_audio_anchor_resonance", "Audio", "Anchor/resonance cue events are produced" },
        { "v31_point_23_audio_pressure_cues", "Audio", "Sentinel pressure cue telemetry is produced" },
        { "v31_point_24_audio_mix_safe_routing", "Audio", "Presentation-safe bus routing is represented" },
        { "v31_point_25_audio_content_pulse_link", "Audio", "Demo charge drives content pulse diagnostics" },
        { "v31_point_26_prod_schema_compatibility", "Production", "Runtime schema compatibility includes v31 metrics" },
        { "v31_point_27_prod_baseline_review", "Production", "Baseline review requires v31 coverage" },
        { "v31_point_28_prod_release_readiness", "Production", "Release readiness includes the v31 manifest" },
        { "v31_point_29_prod_obs_vertical_slice", "Production", "OBS/trailer capture metadata references the vertical slice" },
        { "v31_point_30_prod_docs_roadmap", "Production", "Docs and roadmap document the v31 batch" }
    } };
    return points;
}

const std::array<ProductionFollowupPoint, V32RoadmapPointCount>& GetV32RoadmapPoints()
{
    static const std::array<ProductionFollowupPoint, V32RoadmapPointCount> points = { {
        { "v32_point_01_editor_director_relay_controls", "Editor", "Demo Director exposes phase relay state and controls" },
        { "v32_point_02_editor_viewport_relay_markers", "Editor", "Viewport HUD surfaces relay objective markers" },
        { "v32_point_03_editor_command_macro_relay_route", "Editor", "Command history records the complex relay route macro" },
        { "v32_point_04_editor_readiness_table", "Editor", "Profiler includes the v32 sixty-point readiness table" },
        { "v32_point_05_editor_showcase_workspace", "Editor", "Workspace presets remain ready for public showcase capture" },
        { "v32_point_06_editor_event_route_audit", "Editor", "Gameplay event route audit includes relay events" },
        { "v32_point_07_editor_hud_relay_detail", "Editor", "Public HUD reports relay progress" },
        { "v32_point_08_editor_checkpoint_relay_snapshot", "Editor", "Checkpoints snapshot relay progress metadata" },
        { "v32_point_09_editor_overcharge_stats", "Editor", "Demo Director reports relay overcharge windows" },
        { "v32_point_10_editor_docs_guide", "Editor", "Editor-facing docs describe the v32 demo flow" },
        { "v32_point_11_asset_relay_manifest", "AssetPipeline", "Relay gameplay manifest is assetized for verification" },
        { "v32_point_12_asset_cooked_route_metadata", "AssetPipeline", "Cooked package diagnostics stay valid with the longer route" },
        { "v32_point_13_asset_dependency_replay_v32", "AssetPipeline", "Dependency replay diagnostics cover the v32 batch" },
        { "v32_point_14_asset_relay_material_bindings", "AssetPipeline", "Relay materials use the material binding path" },
        { "v32_point_15_asset_gltf_package_audit", "AssetPipeline", "glTF package audit remains covered during route validation" },
        { "v32_point_16_asset_runtime_promotion_fallback", "AssetPipeline", "Runtime promotion fallbacks are represented in diagnostics" },
        { "v32_point_17_asset_import_cook_review", "AssetPipeline", "Cook/import review tools include v32 manifest coverage" },
        { "v32_point_18_asset_schema_relay_metrics", "AssetPipeline", "Runtime schema includes relay asset and route metrics" },
        { "v32_point_19_asset_prefab_checkpoint_links", "AssetPipeline", "Prefab/checkpoint metadata remains compatible with relays" },
        { "v32_point_20_asset_docs_package_route", "AssetPipeline", "Docs describe asset package expectations for v32" },
        { "v32_point_21_render_relay_glyph_rings", "Rendering", "Phase relays render visible glyph rings" },
        { "v32_point_22_render_relay_bridge_beams", "Rendering", "Stabilized relays render bridge beams" },
        { "v32_point_23_render_objective_beam_upgrade", "Rendering", "Objective hint beam targets relay objectives" },
        { "v32_point_24_render_overcharge_hazard_rings", "Rendering", "Overcharge windows render warning rings" },
        { "v32_point_25_render_rift_charge_relays", "Rendering", "Rift charge responds to relay stabilization" },
        { "v32_point_26_render_vfx_counter_relays", "Rendering", "Runtime report emits relay VFX draw counters" },
        { "v32_point_27_render_csm_route_visibility", "Rendering", "Existing shadow/visibility diagnostics stay valid" },
        { "v32_point_28_render_capture_readability", "Rendering", "Capture path includes relay readability metrics" },
        { "v32_point_29_render_profiler_detail", "Rendering", "Profiler reports renderer-side relay readiness" },
        { "v32_point_30_render_release_capture_schema", "Rendering", "Release capture schema includes v32 render metrics" },
        { "v32_point_31_runtime_relay_stage_machine", "Runtime", "Stage machine includes a relay stabilization phase" },
        { "v32_point_32_runtime_relay_proximity_volumes", "Runtime", "Relay proximity volumes advance objectives" },
        { "v32_point_33_runtime_overcharge_windows", "Runtime", "Relay overcharge windows are tracked" },
        { "v32_point_34_runtime_combo_chain_steps", "Runtime", "Objective combo-chain step counters are tracked" },
        { "v32_point_35_runtime_checkpoint_relays", "Runtime", "Retry/checkpoint flow remains valid with relays" },
        { "v32_point_36_runtime_route_distance_relays", "Runtime", "Objective distance points at relay targets" },
        { "v32_point_37_runtime_deterministic_relay_completion", "Runtime", "Runtime verification completes the relay route deterministically" },
        { "v32_point_38_runtime_stage_telemetry_relays", "Runtime", "Stage telemetry includes relay transitions" },
        { "v32_point_39_runtime_complex_demo_completion", "Runtime", "The longer public demo completes successfully" },
        { "v32_point_40_runtime_gameplay_event_routes", "Runtime", "Gameplay event route counters include relay events" },
        { "v32_point_41_audio_relay_stabilize_cue", "Audio", "Relay stabilization cues are routed through SFX" },
        { "v32_point_42_audio_overcharge_warning_cue", "Audio", "Overcharge warning cue telemetry is represented" },
        { "v32_point_43_audio_combo_confirm_cue", "Audio", "Combo completion cue telemetry is represented" },
        { "v32_point_44_audio_mix_safe_oneshots", "Audio", "One-shot relay cues use mix-safe routing" },
        { "v32_point_45_audio_content_pulse_relays", "Audio", "Relay charge links into content pulse diagnostics" },
        { "v32_point_46_audio_footstep_pressure_coexist", "Audio", "Footstep and pressure cues coexist with relays" },
        { "v32_point_47_audio_backend_fallback_route", "Audio", "XAudio2/WinMM fallback remains covered" },
        { "v32_point_48_audio_meter_relay_coverage", "Audio", "Audio meter coverage includes relay cue runs" },
        { "v32_point_49_audio_cinematic_isolation", "Audio", "Cinematic cue isolation remains available" },
        { "v32_point_50_audio_docs_mix_notes", "Audio", "Docs describe relay cue testing" },
        { "v32_point_51_prod_manifest_v32", "Production", "v32 followup manifest defines sixty points" },
        { "v32_point_52_prod_schema_v32", "Production", "Runtime report schema includes v32 metrics" },
        { "v32_point_53_prod_baselines_v32", "Production", "Verification baselines require v32 relay coverage" },
        { "v32_point_54_prod_runtime_wrapper_v32", "Production", "Runtime wrapper asserts v32 relay metrics" },
        { "v32_point_55_prod_release_readiness_v32", "Production", "Release readiness validates the v32 manifest" },
        { "v32_point_56_prod_perf_history_v32", "Production", "Performance history captures v32 relay counters" },
        { "v32_point_57_prod_baseline_review_v32", "Production", "Baseline review requires v32 keys" },
        { "v32_point_58_prod_docs_roadmap_readme", "Production", "README and roadmap document v32" },
        { "v32_point_59_prod_agents_snapshot", "Production", "AGENTS snapshot describes the v32 batch" },
        { "v32_point_60_prod_version_reporting", "Production", "Version/reporting surfaces v32" }
    } };
    return points;
}

const std::array<ProductionFollowupPoint, V33PlayableDemoPointCount>& GetV33PlayableDemoPoints()
{
    static const std::array<ProductionFollowupPoint, V33PlayableDemoPointCount> points = { {
        { "v33_point_01_collision_arena_bounds", "CollisionTraversal", "Arena collision solves are counted separately from visual bounds" },
        { "v33_point_02_collision_blocker_volumes", "CollisionTraversal", "Blocker volumes stop the player instead of only clamping to the arena" },
        { "v33_point_03_collision_sliding_resolution", "CollisionTraversal", "AABB collision resolution slides the player along the shallow axis" },
        { "v33_point_04_traversal_vault_barriers", "CollisionTraversal", "Traversable low barriers can be vaulted or dashed through" },
        { "v33_point_05_traversal_dash_cooldown", "CollisionTraversal", "Dash/vault traversal has cooldown telemetry" },
        { "v33_point_06_traversal_visual_markers", "CollisionTraversal", "Traversal barriers render as readable public-demo markers" },
        { "v33_point_07_traversal_verification_route", "CollisionTraversal", "Runtime verification exercises the collision/traversal route" },
        { "v33_point_08_traversal_audio_feedback", "CollisionTraversal", "Traversal actions fire content-backed cue telemetry" },
        { "v33_point_09_traversal_hud_telemetry", "CollisionTraversal", "HUD and director expose collision/traversal counts" },
        { "v33_point_10_traversal_schema_baseline", "CollisionTraversal", "Schema and baselines require traversal coverage" },
        { "v33_point_11_enemy_patrol_home", "EnemyAI", "Public-demo enemies patrol from authored home positions" },
        { "v33_point_12_enemy_aggro_radius", "EnemyAI", "Enemies enter chase state inside an aggro radius" },
        { "v33_point_13_enemy_chase_motion", "EnemyAI", "Enemies move toward the player while alerted" },
        { "v33_point_14_enemy_contact_pressure", "EnemyAI", "Enemy contact drains stability and feeds pressure telemetry" },
        { "v33_point_15_enemy_dash_evade", "EnemyAI", "Dash timing can evade or stun a chasing enemy" },
        { "v33_point_16_enemy_failure_retry", "EnemyAI", "Enemy pressure can trigger the authored retry presentation" },
        { "v33_point_17_enemy_visual_language", "EnemyAI", "Enemies draw vision rings and chase beams for public readability" },
        { "v33_point_18_enemy_director_stats", "EnemyAI", "Demo Director exposes chase, evade, and contact counters" },
        { "v33_point_19_enemy_verification_route", "EnemyAI", "Runtime verification deterministically exercises enemy behavior" },
        { "v33_point_20_enemy_audio_cues", "EnemyAI", "Enemy contact and evade events use content-backed cue routing" },
        { "v33_point_21_menu_pause_flow", "GamepadMenu", "A visible pause/menu flow can gate gameplay" },
        { "v33_point_22_menu_completion_flow", "GamepadMenu", "Completion transitions the public demo into a completed menu state" },
        { "v33_point_23_gamepad_xinput_loader", "GamepadMenu", "XInput is loaded dynamically without adding external dependencies" },
        { "v33_point_24_gamepad_left_stick_move", "GamepadMenu", "Left stick contributes to player movement input" },
        { "v33_point_25_gamepad_start_pause", "GamepadMenu", "Start button toggles pause/play menu state" },
        { "v33_point_26_gamepad_a_traversal", "GamepadMenu", "A button maps to dash/vault traversal" },
        { "v33_point_27_gamepad_runtime_simulation", "GamepadMenu", "Runtime verification simulates gamepad frames without hardware" },
        { "v33_point_28_gamepad_hud_hint", "GamepadMenu", "HUD documents keyboard and controller play inputs" },
        { "v33_point_29_gamepad_menu_metrics", "GamepadMenu", "Runtime report emits gamepad/menu counters" },
        { "v33_point_30_gamepad_schema_baseline", "GamepadMenu", "Schema and baseline review require gamepad/menu coverage" },
        { "v33_point_31_failure_overlay", "FailurePresentation", "Retry failure shows a dedicated overlay rather than only a status line" },
        { "v33_point_32_failure_reason_text", "FailurePresentation", "Failure presentation stores and displays a reason string" },
        { "v33_point_33_failure_checkpoint_return", "FailurePresentation", "Failure returns the player to the latest checkpoint" },
        { "v33_point_34_failure_stability_recovery", "FailurePresentation", "Retry restores enough stability to continue play" },
        { "v33_point_35_failure_event_log", "FailurePresentation", "Failure and retry events are recorded in the public event log" },
        { "v33_point_36_failure_audio_cue", "FailurePresentation", "Failure retry fires content-backed cue telemetry" },
        { "v33_point_37_failure_verification_trigger", "FailurePresentation", "Runtime verification forces failure presentation coverage" },
        { "v33_point_38_failure_director_button", "FailurePresentation", "Demo Director retry button feeds the same presentation path" },
        { "v33_point_39_failure_menu_interop", "FailurePresentation", "Failure presentation coexists with pause/completion menu states" },
        { "v33_point_40_failure_schema_baseline", "FailurePresentation", "Schema and baseline review require failure presentation coverage" },
        { "v33_point_41_audio_cue_manifest", "AudioAnimation", "Public demo cue definitions are read from an asset manifest" },
        { "v33_point_42_audio_named_cues", "AudioAnimation", "Shard, traversal, enemy, failure, and completion cues use named definitions" },
        { "v33_point_43_audio_spatial_content_hooks", "AudioAnimation", "Content cues route through spatial or bus playback helpers" },
        { "v33_point_44_audio_nonspam_cooldowns", "AudioAnimation", "Content cue counters avoid frame-spam by firing on state changes" },
        { "v33_point_45_animation_manifest", "AudioAnimation", "Public demo animation states are read from an asset manifest" },
        { "v33_point_46_animation_state_machine", "AudioAnimation", "Player idle/walk/sprint/dash/failure/complete states are tracked" },
        { "v33_point_47_animation_visual_feedback", "AudioAnimation", "Player material feedback changes with animation state" },
        { "v33_point_48_animation_runtime_metrics", "AudioAnimation", "Runtime report emits animation state change counters" },
        { "v33_point_49_content_assets_verified", "AudioAnimation", "Runtime verification asserts content-backed cue and animation assets" },
        { "v33_point_50_docs_roadmap_agents_v33", "AudioAnimation", "README, roadmap, and agent context document the v33 playable batch" }
    } };
    return points;
}

const std::array<ProductionFollowupPoint, V34AAAFoundationPointCount>& GetV34AAAFoundationPoints()
{
    static const std::array<ProductionFollowupPoint, V34AAAFoundationPointCount> points = { {
        { "v34_point_01_enemy_archetype_catalog", "EncounterAI", "Public demo has distinct hunter, warden, and disruptor enemy roles" },
        { "v34_point_02_enemy_los_checks", "EncounterAI", "Enemy behavior evaluates simple line-of-sight checks against blockers" },
        { "v34_point_03_enemy_patrol_offsets", "EncounterAI", "Enemy patrols use authored offsets per archetype" },
        { "v34_point_04_enemy_telegraph_windows", "EncounterAI", "Enemies expose readable attack telegraph windows" },
        { "v34_point_05_enemy_hit_reactions", "EncounterAI", "Dash evasion creates hit-reaction telemetry" },
        { "v34_point_06_enemy_pressure_roles", "EncounterAI", "Enemy roles apply pressure through different ranges and speeds" },
        { "v34_point_07_enemy_archetype_visuals", "EncounterAI", "Enemy archetypes have distinct readable materials and rings" },
        { "v34_point_08_enemy_director_readout", "EncounterAI", "Demo Director reports archetype and telegraph counters" },
        { "v34_point_09_enemy_verification_route", "EncounterAI", "Runtime verification exercises archetype, line-of-sight, and hit reaction coverage" },
        { "v34_point_10_enemy_schema_baseline", "EncounterAI", "Schema and baselines require encounter-AI coverage" },
        { "v34_point_11_controller_grounding", "Controller", "Public demo controller records grounded frames" },
        { "v34_point_12_controller_slope_probe", "Controller", "Controller samples authored slope readiness" },
        { "v34_point_13_controller_material_friction", "Controller", "Controller records material/friction surface samples" },
        { "v34_point_14_controller_moving_platform", "Controller", "Controller has moving-platform readiness telemetry" },
        { "v34_point_15_controller_camera_collision", "Controller", "Third-person camera collision avoidance is tracked" },
        { "v34_point_16_controller_coyote_time", "Controller", "Controller exposes coyote-time style grace diagnostics" },
        { "v34_point_17_controller_dash_recovery", "Controller", "Dash recovery contributes to controller polish telemetry" },
        { "v34_point_18_controller_accessibility_speed", "Controller", "Accessibility movement scaling is represented in runtime state" },
        { "v34_point_19_controller_runtime_metrics", "Controller", "Runtime report emits controller polish counters" },
        { "v34_point_20_controller_visible_polish", "Controller", "Playable route shows controller/platform/camera polish markers" },
        { "v34_point_21_animation_blend_tree_manifest", "Animation", "Public demo loads a blend-tree manifest asset" },
        { "v34_point_22_animation_clip_events", "Animation", "Animation event markers are parsed and counted" },
        { "v34_point_23_animation_root_motion_preview", "Animation", "Root-motion preview metadata is represented" },
        { "v34_point_24_animation_state_transition_table", "Animation", "Blend-tree transitions are counted" },
        { "v34_point_25_animation_event_audio_hooks", "Animation", "Animation event route can fire content-backed cue hooks" },
        { "v34_point_26_animation_debug_readout", "Animation", "Demo Director exposes blend-tree and event counts" },
        { "v34_point_27_animation_verification_route", "Animation", "Runtime verification exercises blend-tree coverage" },
        { "v34_point_28_animation_asset_docs", "Animation", "Animation asset path is documented for future sessions" },
        { "v34_point_29_animation_metrics_schema", "Animation", "Schema and baselines require animation event metrics" },
        { "v34_point_30_animation_future_gpu_skinning_gate", "Animation", "Animation metrics reserve the future GPU-skinning gate" },
        { "v34_point_31_editor_title_flow_preview", "EditorUX", "Editor/runtime state includes title-flow preview readiness" },
        { "v34_point_32_editor_settings_accessibility", "EditorUX", "Settings and accessibility toggles are represented" },
        { "v34_point_33_editor_chapter_select", "EditorUX", "Chapter-select readiness is tracked" },
        { "v34_point_34_editor_save_slot_surface", "EditorUX", "Save-slot surface readiness is tracked" },
        { "v34_point_35_editor_command_macro_fixture", "EditorUX", "Command-history macro fixture is recorded for v34" },
        { "v34_point_36_editor_nested_prefab_readiness", "EditorUX", "Nested-prefab readiness remains in the v34 gate" },
        { "v34_point_37_editor_gizmo_depth_readiness", "EditorUX", "Depth-aware gizmo/readback readiness remains in the v34 gate" },
        { "v34_point_38_editor_director_aaa_table", "EditorUX", "Demo Director exposes an AAA foundations readiness table" },
        { "v34_point_39_editor_runtime_report_diff", "EditorUX", "Runtime report includes v34 editor/UX counters" },
        { "v34_point_40_editor_docs_agent_update", "EditorUX", "README, roadmap, and agent context document v34" },
        { "v34_point_41_render_csm_stabilization_metric", "Rendering", "Rendering readiness tracks CSM stabilization coverage" },
        { "v34_point_42_render_motion_vector_coverage", "Rendering", "Rendering readiness tracks motion-vector/TAA coverage" },
        { "v34_point_43_render_taa_resolve_gate", "Rendering", "TAA resolve readiness is represented in v34 metrics" },
        { "v34_point_44_render_clustered_light_readiness", "Rendering", "Clustered/Forward+ light-bin readiness is represented" },
        { "v34_point_45_render_vfx_overdraw_budget", "Rendering", "VFX overdraw budget readiness is represented" },
        { "v34_point_46_render_capture_tile_async_gate", "Rendering", "Async tiled capture readiness is represented" },
        { "v34_point_47_render_ssr_ssgi_placeholders", "Rendering", "SSR/SSGI roadmap placeholders are carried into readiness" },
        { "v34_point_48_render_gpu_culling_budget", "Rendering", "GPU culling budget readiness is represented" },
        { "v34_point_49_render_debug_view_parity", "Rendering", "Debug-view parity is represented in v34 metrics" },
        { "v34_point_50_render_schema_baseline", "Rendering", "Schema and baselines require rendering readiness counters" },
        { "v34_point_51_production_release_manifest_v34", "Production", "Release-readiness review includes the v34 manifest" },
        { "v34_point_52_production_runtime_schema_v34", "Production", "Runtime schema includes the v34 metrics" },
        { "v34_point_53_production_baseline_review_v34", "Production", "Baseline review requires v34 counters" },
        { "v34_point_54_production_perf_history_v34", "Production", "Performance history records v34 counters" },
        { "v34_point_55_production_smoke_runtime_v34", "Production", "Smoke/runtime verification gates cover v34" },
        { "v34_point_56_production_interactive_ci_v34", "Production", "Interactive CI planning accounts for v34 artifacts" },
        { "v34_point_57_production_package_artifact_v34", "Production", "Packaging/release artifacts remain checked under v34" },
        { "v34_point_58_production_obs_capture_v34", "Production", "OBS capture metadata remains checked under v34" },
        { "v34_point_59_production_public_showcase_notes", "Production", "Public-showcase notes are updated for v34" },
        { "v34_point_60_production_version_agent_snapshot", "Production", "Versioning and AGENTS snapshot describe v34" }
    } };
    return points;
}

const std::array<ProductionFollowupPoint, V35EngineArchitecturePointCount>& GetV35EngineArchitecturePoints()
{
    static const std::array<ProductionFollowupPoint, V35EngineArchitecturePointCount> points = { {
        { "v35_point_01_event_bus_module", "Core", "Engine has an owned event bus module" },
        { "v35_point_02_event_bus_subscription", "Core", "Typed event subscriptions deliver callbacks" },
        { "v35_point_03_event_bus_wildcard_route", "Core", "Wildcard event observers can audit traffic" },
        { "v35_point_04_event_bus_queue_flush", "Core", "Queued events flush deterministically" },
        { "v35_point_05_event_bus_diagnostics", "Core", "Event bus diagnostics expose subscriber, delivery, and queue stats" },
        { "v35_point_06_event_bus_dropped_counter", "Core", "Unrouted event drops are tracked" },
        { "v35_point_07_event_bus_max_depth", "Core", "Maximum queue depth is recorded" },
        { "v35_point_08_event_bus_runtime_report", "Core", "Runtime verification reports event bus counters" },
        { "v35_point_09_event_bus_manifest", "Core", "Followup manifest includes event bus coverage" },
        { "v35_point_10_event_bus_public_header", "Core", "Event bus is exposed through the engine umbrella include" },
        { "v35_point_11_scheduler_module", "Runtime", "Engine has an owned frame scheduler module" },
        { "v35_point_12_scheduler_phase_catalog", "Runtime", "Scheduler defines input, simulation, physics, animation, audio, rendering, and editor phases" },
        { "v35_point_13_scheduler_priority_order", "Runtime", "Tasks execute in deterministic priority order within phases" },
        { "v35_point_14_scheduler_disable_path", "Runtime", "Disabled scheduler tasks are skipped and counted" },
        { "v35_point_15_scheduler_execution_order", "Runtime", "Last frame execution order is queryable" },
        { "v35_point_16_scheduler_diagnostics", "Runtime", "Scheduler diagnostics expose registered, executed, skipped, and frame counts" },
        { "v35_point_17_scheduler_phase_coverage", "Runtime", "Runtime verification executes every engine phase" },
        { "v35_point_18_scheduler_runtime_report", "Runtime", "Runtime report emits scheduler counters" },
        { "v35_point_19_scheduler_manifest", "Runtime", "Followup manifest includes scheduler coverage" },
        { "v35_point_20_scheduler_public_header", "Runtime", "Frame scheduler is exposed through the engine umbrella include" },
        { "v35_point_21_scene_query_module", "Scene", "Engine has an owned scene query world module" },
        { "v35_point_22_scene_query_stable_ids", "Scene", "Scene query entries keep stable object IDs and names" },
        { "v35_point_23_scene_query_sphere", "Scene", "Sphere overlap queries return hits" },
        { "v35_point_24_scene_query_aabb", "Scene", "AABB overlap queries return hits" },
        { "v35_point_25_scene_query_raycast", "Scene", "Raycasts return nearest scene query hits" },
        { "v35_point_26_scene_query_layers", "Scene", "Layer masks reject filtered scene query entries" },
        { "v35_point_27_scene_query_diagnostics", "Scene", "Scene query diagnostics count entries, queries, raycasts, and hits" },
        { "v35_point_28_scene_query_runtime_report", "Scene", "Runtime report emits scene query counters" },
        { "v35_point_29_scene_query_manifest", "Scene", "Followup manifest includes scene query coverage" },
        { "v35_point_30_scene_query_public_header", "Scene", "Scene query is exposed through the engine umbrella include" },
        { "v35_point_31_streaming_plan_module", "Assets", "Engine has an asset streaming plan module" },
        { "v35_point_32_streaming_priority_sort", "Assets", "Asset streaming requests are scheduled by priority" },
        { "v35_point_33_streaming_budget_defer", "Assets", "Streaming budgets can defer lower priority requests" },
        { "v35_point_34_streaming_pinned_cancel_guard", "Assets", "Pinned streaming requests resist cancellation" },
        { "v35_point_35_streaming_dependency_edges", "Assets", "Streaming diagnostics count dependency edges" },
        { "v35_point_36_streaming_scheduled_bytes", "Assets", "Streaming diagnostics count scheduled bytes" },
        { "v35_point_37_streaming_runtime_report", "Assets", "Runtime report emits streaming counters" },
        { "v35_point_38_streaming_public_header", "Assets", "Asset streaming plan is exposed through the engine umbrella include" },
        { "v35_point_39_render_graph_budget_module", "Rendering", "Engine has a render-graph budget analyzer module" },
        { "v35_point_40_render_graph_budget_passes", "Rendering", "Render-graph pass counts are budgeted" },
        { "v35_point_41_render_graph_budget_resources", "Rendering", "Render-graph resource counts are budgeted" },
        { "v35_point_42_render_graph_budget_barriers", "Rendering", "Render-graph barrier counts are budgeted" },
        { "v35_point_43_render_graph_budget_aliases", "Rendering", "Render-graph alias reuse can be required" },
        { "v35_point_44_render_graph_budget_warnings", "Rendering", "Budget analysis records warning strings" },
        { "v35_point_45_render_graph_budget_runtime_report", "Rendering", "Runtime report emits render-graph budget counters" },
        { "v35_point_46_engine_module_smoke_tests", "Production", "Runtime verifier smokes every v35 engine module" },
        { "v35_point_47_engine_baseline_gates", "Production", "Baseline assets require v35 engine counters" },
        { "v35_point_48_engine_schema_gates", "Production", "Runtime schema requires v35 engine metrics and point keys" },
        { "v35_point_49_engine_docs_roadmap", "Production", "Docs and roadmap describe the engine-first v35 batch" },
        { "v35_point_50_engine_version_agent_snapshot", "Production", "Versioning and AGENTS snapshot describe v35" }
    } };
    return points;
}

}
